apiVersion: v1
kind: ConfigMap
metadata:
  name: musiceshop-app-config
  namespace: musiceshop
  labels:
    app: musiceshop
    component: web
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
