apiVersion: v1
kind: Service
metadata:
  name: musiceshop-web-service
  namespace: musiceshop
  labels:
    app: musiceshop
    component: web
spec:
  type: ClusterIP
  selector:
    app: musiceshop
    component: web
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
