apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: musiceshop
  labels:
    app: musiceshop
    component: database
spec:
  type: ClusterIP
  selector:
    app: musiceshop
    component: database
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: mssql
