apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: musiceshop

resources:
  - namespace.yaml

  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml

secretGenerator:
  - name: musiceshop-app-secret
    envs:
      - .env
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      managed-by: kustomize
